modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "cobblenotify"
version = "${version}"
displayName = "CobbleNotify"
logoFile = "icon.png"
authors = ["Zonary123"]
credits = "Zonary123"
displayURL = "https://github.com/zonary123/CobbleSpawnNotify"
description = '''

'''
[[dependencies.cobblenotify]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.cobblenotify]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,]"
ordering = "NONE"
side = "BOTH"
[[dependencies.cobblenotify]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.2,]"
ordering = "NONE"
side = "BOTH"