architectury {
    common("fabric")
    common("neoforge")
}

loom {
    //accessWidenerPath = file("src/main/resources/cobblenotify.accesswidener")
}

dependencies {

    modImplementation("com.cobblemon:fabric:${property("cobblemon_version")}")
    // alL fabric dependencies:
    modImplementation("net.fabricmc:fabric-loader:${property("fabric_loader_version")}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${property("fabric_version")}")
    modImplementation("net.neoforged:neoforge:${rootProject.neoforge_version}")
    modImplementation("dev.architectury:architectury:${property("architectury_version")}")
    modImplementation("ca.landonjw.gooeylibs:fabric-api-repack:${property("gooeylibs_version")}")


    modImplementation(files("libs/CobbleUtils-common-1.1.3.jar"))

    // Lombok
    annotationProcessor("org.projectlombok:lombok:${property("lombok_version")}")
    implementation("org.projectlombok:lombok:${property("lombok_version")}")

    // Permissions
    api("net.luckperms:api:${property("luckperms_version")}")
    modImplementation("me.lucko:fabric-permissions-api:0.3.3")

    // Kyori Adventure
    api("net.kyori:adventure-text-serializer-gson:${property("kyori_version")}")
    api("net.kyori:adventure-text-minimessage:${property("kyori_version")}")

    //Discord
    api("club.minnced:discord-webhooks:${property("discord_webhooks_version")}")


}

test {
    useJUnitPlatform()
    // Since JDK 21
    // ref: https://stackoverflow.com/questions/77951485/getting-a-java-agent-has-been-loaded-warning-in-intellij-after-upgrading-jdk-17
    jvmArgs("-XX:+EnableDynamicAgentLoading")
}


